spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  main:
    allow-circular-references: true

  data:
    mongodb:
      uri: mongodb+srv://shaunak436:emmanuel123@cluster0.igrxhvt.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shaunak436@gmail.com
    password: roum wxbl szmb ssjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  redis:
    data:
      host: redis-14443.crce263.ap-south-1-1.ec2.cloud.redislabs.com
      port: 14443
      password: aWFWBidJ15NibqROyQWcs2yMtIhv59sS



  kafka:
      bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092

      client-id: ccloud-springboot-client-1db5c95b-900a-4e2c-b88b-ede5832ea71f

      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='XKN3TGJ56IFJXMYP' password='cfltyO0f+xRwMYDeaUnpI0tD1aeIPg8tvEETW5LC1wT7CCrpSNpKm5CzC5OkzXPw';
        session.timeout.ms: 45000

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      consumer:
        group-id: topic_0
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: com.shaunak.journal.model


weather:
  api:
    key: ec849122a324ca5e6edcd7fc4ec42a45

jwt:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V